version: "3.5"
services:
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}-alpine
        ALPINE_MIRRORS: ${ALPINE_MIRRORS}
        NGINX_INSTALL_CERTBOT: ${NGINX_INSTALL_CERTBOT}
        TZ: ${TZ}
    container_name: nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${ROOT_DIR}:/www/:rw
      - ${NGINX_SSL_DIR}:/etc/nginx/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - dnmp


  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: ${PHP_VERSION}-fpm-alpine
        ALPINE_MIRRORS: ${ALPINE_MIRRORS}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: ${TZ}
    container_name: php
    expose:
      - 9000
    extra_hosts:
      - "www.site1.com:172.17.0.1"
    volumes:
      - ${ROOT_DIR}:/www/:rw
      - ${PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    networks:
      - dnmp


  mysql5:
    image: mysql:${MYSQL5_VERSION}
    container_name: mysql5
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
    restart: always
    networks:
      - dnmp
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL5_ROOT_PASSWORD}"
      TZ: "$TZ"


  redis:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - dnmp



networks:
  dnmp:
    name: dnmp
